export const CreateNoteActionTypes = {
  SET_TITLE: 'SET_TITLE',
  SET_DESCRIPTION: 'SET_DESCRIPTION',
  SET_BACKGROUND: 'SET_BACKGROUND', 
  SET_IS_ARCHIVED: 'SET_IS_ARCHIVED',
  SET_IS_PINNED: 'SET_IS_PINNED',
  SET_IS_COMPLETED: 'SET_IS_COMPLETED',
  RESET_STATE: 'RESET_STATE'
}