export const NoteActionTypes = {
  ADD_COLLECTION: 'ADD_COLLECTION',
  ADD_NOTE: 'ADD_NOTE',
  REMOVE_NOTE: 'REMOVE_NOTE',
  EDIT_NOTE: 'EDIT_NOTE',
  FILTER_NOTES: 'FILTER_NOTES',
  FETCH_START: 'FETCH_START',
  FETCH_SUCCESS: 'FETCH_SUCCESS',
  FETCH_FAILURE: 'FETCH_FAILURE'
}