export const HeaderActionTypes = {
  TOGGLE_MENU_OPEN: "TOGGLE_MENU_OPEN",
  SET_SEARCH_FOCUSED: "SET_SEARCH_FOCUSED",
  SET_SEARCH_VALUE: "SET_SEARCH_VALUE", 
  TOGGLE_REFRESH: "TOGGLE_REFRESH",
  TOGGLE_LIST_VIEW: "TOGGLE_LIST_VIEW",
  TOGGLE_THEME: "TOGGLE_THEME"
}