export const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',  
  LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
  LOGOUT_SUCCESSFUL: 'LOGOUT_SUCCESSFUL',
  FETCH_START: 'FETCH_START',  
  FETCH_FAILURE: 'FETCH_FAILURE'
}